### PR TITLE
Add first version of deployment on dev script

### PR DESCRIPTION
**Pull request by minottic**
@stephan271 , @wakonig this would be the first version of the deployment script. Unfortunately, I've checked the git client hooks and the post-push does not exist.

This script might change (depending on what you need). For now, the idea is that using this script, [steps](https://github.com/paulscherrerinstitute/scicat-ci#workflow-when-working-on-a-submodule) 1, 7, (8 partially) are automated. 
This script has to be run from the scilog-ci folder, every time one wants to deploy. 
It can be modified to run directly in the scilog (submodule) folder to cover points 2 and 6 (`cd` commands).

Let me know if it is good enough or needs changing.

### CODE REVIEW

**Comment by stephan271** [comment]
Did you think about the option to have no branches for scilog-ci for "normal" development updates ?

**Comment by minottic** [comment]
I still haven't understood what is the idea on that ....

**Comment by wakonig** [comment]
I guess the idea was to only have a single branch in scilog-ci and automatically deploy whatever is on main. We test locally, discuss the PR on git, merge it, test it on our dev server and potentially later deploy it on production. 
By skipping the ci branches, it is always clear what is currently deployed on dev

**Comment by minottic** [comment]
now the deployment has 3 steps: to dev, to qa, to prod. What you described is actually what happens in qa. I still struggle to understand what it simplifies, it only removes the PR opening need

**Comment by wakonig** [comment]
Okay, now I'm also confused... I understood that there is no automatic deployment from scilog main?

**Comment by minottic** [comment]
everything it's more or less explained here: https://github.com/paulscherrerinstitute/scicat-ci/#scicat-ci (happy to discuss further ofc)

**Pull request merged**
